[api]
database_user = "postgres"
database_password = "fidesctl"
database_host = "fidesctl-db"
database_port = "5432"
database_name = "fidesctl"

test_database_name = "fidesctl_test"

[cli]
# Decompose this
server_url = "http://fidesctl:8080"

[user]
analytics_opt_out = false
