[database]
server="fidesctl-db"
user="postgres"
password="fidesctl"
port="5432"
db="fidesctl"
test_db="fidesctl_test"

[logging]
level = "INFO"

[cli]
server_host = "localhost"
server_port = 8080

[user]
analytics_opt_out = false
