[api]
database_user = "postgres"
database_password = "fidesctl"
database_host = "localhost"
database_port = "5432"
database_name = "fidesctl"
test_database_name = "fidesctl_test"

[cli]
server_host = "localhost"
server_port = 8080
analytics_id = "d615f75e813f4b34ac29a26877f0824b"

[user]
analytics_opt_out = false
