[database]
server="fides-db"
user="postgres"
password="fides"
port="5432"
db="fides"
test_db="fides_test"

[logging]
level = "INFO"

[cli]
server_host = "localhost"
server_port = 8080

[user]
analytics_opt_out = false
