name: Docker Build & Push

on:
  push:
    branches:
      - main

jobs:
  push-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Log In
        run: docker login

      - name: Build & Push the Server
        run: make server-push

  push-cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Log In
        run: docker login

      - name: Build & Push the CLI
        run: make server-push
